### ISSUE TITLE
Where does mkvirtualenv command come from

### ISSUE THREAD

**Issue by alnutile** [bennybauer/serverless-python-sample#4]
Thanks for the example.

You mention this in your readme.md but I do not see a step to install it.

Cheers
Al

**Comment by bennybauer** [comment]
I'm using virtualenvwrapper, see [link](https://virtualenvwrapper.readthedocs.io/en/latest/) for install instructions.

**Comment by bennybauer** [comment]
updated README with link to virtualenvwrapper.

**Comment by alnutile** [comment]
Thanks!
