### ISSUE TITLE
link to `Set up an AWS account with admin permissions` is broken

### ISSUE THREAD

**Issue by stubbi** [bennybauer/serverless-python-sample#6]
In
```
# Usage
## Setup
| **Step** | **Command** |**Description**|
|---|-------|------|
|  1. | `npm install -g serverless` | Install Serverless CLI  |
|  2. | `npm install` | Install Serverless dependencies  |
|  3. | Set up an AWS account with admin permissions | [Documentation](https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/credentials.md)  |
```
[The link for Set up an AWS account with admin permissions](https://github.com/serverless/serverless/blob/master/docs/02-providers/aws/01-setup.md) returns a 404. From the [serverless repo](https://github.com/serverless/serverless) it looks like [this](https://github.com/serverless/serverless/blob/master/docs/providers/aws/guide/credentials.md) is the new link.

**Comment by bennybauer** [comment]
Thanks! I've updated it now ([8c76d75](https://github.com/bennybauer/serverless-python-sample/commit/8c76d7555f85366762026bbeb1bdf36707b8a816))
